const geocodingResponse = [
	{
		name: 'Chicago',
		local_names: {
			ar: 'شيكاغو',
			ascii: 'Chicago',
			az: 'Çikaqo',
			bg: 'Чикаго',
			ca: 'Chicago',
			da: 'Chicago',
			de: 'Chicago',
			el: 'Σικάγο',
			en: 'Chicago',
			eu: 'Chicago',
			fa: 'شیکاگو',
			feature_name: 'Chicago',
			fi: 'Chicago',
			fr: 'Chicago',
			gl: 'Chicago',
			he: 'שיקגו',
			hi: 'शिकागो',
			hr: 'Chicago',
			hu: 'Chicago',
			id: 'Chicago',
			it: 'Chicago',
			ja: 'シカゴ',
			la: 'Sicagum',
			lt: 'Čikaga',
			mk: 'Чикаго',
			nl: 'Chicago',
			no: 'Chicago',
			pl: 'Chicago',
			pt: 'Chicago',
			ro: 'Chicago',
			ru: 'Чикаго',
			sk: 'Chicago',
			sl: 'Chicago',
			sr: 'Чикаго',
			th: 'ชิคาโก',
			tr: 'Şikago',
			vi: 'Chicago',
		},
		lat: 41.85,
		lon: -87.65,
		country: 'US',
		state: 'IL',
	},
];
